#!/usr/bin/python
import os, sys

ERROR_NOT_RUN      = -1
ERROR_USER_ABORTED = -2
ERROR_UNKNOWN      = -3

INSTALLATION_ABORTED = 'Installation aborted.'

WHIZBANG = os.path.dirname(os.path.realpath(__file__))
MODULES  = os.path.sep.join((WHIZBANG, 'modules'))
GLOYDIUS = os.path.sep.join((MODULES, 'gloydius'))

if __name__ != '__main__':
    print "You must simply run the installation script."
    exit(ERROR_NOT_RUN)

def install_file(source, target): install.symlink(os.path.sep.join((HOME, target)), os.path.sep.join((WHIZBANG, 'conf', source)), BACKUP)

def ini_config(ini, changes):
    sections = {}
    for name, params in changes.iteritems(): sections[name.join(('[', ']'))] = params
    install.ini_config(os.path.sep.join((HOME, ini)), sections, BACKUP)

try:
    if not os.path.isdir(GLOYDIUS):
        print 'Whizbang requires Gloydius python libraries to work. Would you like to download it now? (yes/no)'
        while True:
            answer = raw_input().lower()
            if answer == 'no':
                print INSTALLATION_ABORTED
                exit(ERROR_USER_ABORTED)
            if answer != 'yes':
                print "Please just type 'yes' or 'no'"
                continue
            code = os.system('cd {}; git clone git@github.com:grief/gloydius.git'.format(MODULES))
            if code != 0:
                print "Cloning from git failed with error {}. You may check the above output. {}".format(code, INSTALLATION_ABORTED)
                exit(ERROR_UNKNOWN)
            break

    sys.path.append(GLOYDIUS)
    import install

    HOME   = os.path.expanduser('~')
    BACKUP = os.path.sep.join((WHIZBANG, 'backup'))  # None for disabling backing up

    SHELL  = os.path.basename(os.environ['SHELL'])

    if SHELL == 'zsh':
        for name in ['.zshenv', '.zprofile', '.zshrc', '.zlogin', '.zlogout']: install_file('event-handler', name)

    install_file('conky.conf', '.conkyrc')

    install_file('event-handler', '.config/autostart/de-startup')

    ini_config('.kde/share/config/kdeglobals', {'Paths': {'Autostart[$e]': '/g/components/kde/autostart'}})

except KeyboardInterrupt: print INSTALLATION_ABORTED
